

Create TRIGGER A8
ON DETAILRENTAL  
AFTER UPDATE    
AS  
BEGIN  
 
DECLARE @RENT_NUM CHAR   
DECLARE @PRIOR_DAYS_LATE INT 
DECLARE @DAYS_LATE INT
DECLARE @DAILY_LATE_FEE DECIMAL (5,2)   
DECLARE @PRIOR_UPDATE DECIMAL (5,2)  
DECLARE @AFTER_UPDATE DECIMAL (5,2) 
DECLARE @UPDATED_LATE_FEE DECIMAL (5,2) 
 
IF(EXISTS (SELECT * FROM DELETED) AND EXISTS (SELECT * FROM INSERTED)) BEGIN  
 
DECLARE UPDATE_CURSOR CURSOR 
FOR SELECT I.RENT_NUM, DATEDIFF(DAY, D.DETAIL_DUEDATE, D.DETAIL_RETURNDATE) AS PRIOR_DAYS_LATE,    
DATEDIFF(DAY, I.DETAIL_DUEDATE, I.DETAIL_RETURNDATE) AS DAYS_LATE, I.DETAIL_DAILYLATEFEE  
FROM INSERTED I INNER JOIN DELETED D ON I.RENT_NUM = D.RENT_NUM AND I.VID_NUM = D.VID_NUM  
 
OPEN UPDATE_CURSOR  
FETCH NEXT FROM UPDATE_CURSOR 
INTO @RENT_NUM, @PRIOR_DAYS_LATE, @DAYS_LATE, @DAILY_LATE_FEE  
WHILE (@@FETCH_STATUS = 0)  
 
IF @DAYS_LATE IS NULL     
BEGIN     
SET @AFTER_UPDATE = 0     
END   
ELSE     
BEGIN      
SET @AFTER_UPDATE = (@DAYS_LATE * @DAILY_LATE_FEE)     
END  

 IF  ((@AFTER_UPDATE - @PRIOR_UPDATE) <> 0)    
 BEGIN     
 SET @UPDATED_LATE_FEE = (@AFTER_UPDATE - @PRIOR_UPDATE)     
 END    
 ELSE     
 BEGIN     
 SET @UPDATED_LATE_FEE = 0    
 END    

 BEGIN    
 UPDATE MEMBERSHIP    
 SET  MEM_BALANCE = MEM_BALANCE + @UPDATED_LATE_FEE    
 WHERE MEM_NUM = (SELECT MEM_NUM FROM RENTAL WHERE RENT_NUM = @RENT_NUM)   
 END    
 FETCH NEXT 
 FROM UPDATE_CURSOR 
 INTO @RENT_NUM, @DAYS_LATE, @DAILY_LATE_FEE  
 END   
 CLOSE UPDATE_CURSOR   
 DEALLOCATE UPDATE_CURSOR  

 END  



--TEST CODE

--transactions for testing
select *
from DETAILRENTAL
Where Rent_Num = '1006' or Rent_Num = '1007'

--setting return date
update DETAILRENTAL
set Detail_ReturnDate = '3/9/2013'
where Rent_Num = '1006' and Vid_Num = '61367'

update DETAILRENTAL
set Detail_ReturnDate = '3/9/2013'
where Rent_Num = '1007'

--check to see that balance changed on update
select Rent_Num, Mem_Balance
from MEMBERSHIP M join RENTAL R on M.Mem_Num = R.Mem_Num
where Rent_Num = '1006' or Rent_Num = '1007'

--update return date back to original value of null
update DETAILRENTAL
set Detail_ReturnDate = null
where Rent_Num = '1007'

update DETAILRENTAL
set Detail_ReturnDate = null
where Rent_Num = '1006' and Vid_Num = '61367'